### ISSUE TITLE
Need Help !!!!!

### ISSUE THREAD

**Issue by ghost** [mhdzumair/MhDzMR-Kernel-Nicklaus#1]
Hi there,

Is it for moto e4 plus Nicklaus Mediatek XT1770, android 7.1.1, kernel 3.18.35+ variant if yes then which toolchain do i need arm or arm64 and which defconfig in arm folder or arm64 folder ????

Regards

**Comment by mhdzumair** [comment]
Yes. I used linaro arm GCC the latest one. Put the linaro toolchain in kernel folder.  Nicklaus is arm, there is a nicklaus_defconfig. You don't need to manually type. There is compiler script just type  below command in kernel folder.
./compile

**Comment by ghost** [comment]
> Yes. I used linaro arm GCC the latest one. Put the linaro toolchain in kernel folder. Nicklaus is arm, there is a nicklaus_defconfig. You don't need to manually type. There is compiler script just type below command in kernel folder.
> ./compile

Some files were missing but dont worry I collected them. I want to know something every time I flash a custom kernel on this phone its either no volte or no usb otg/ usb storage even lsusb dosent show anything.

Should I flash magisk after kernel or before kernel and do i need dm-verity ?

**Comment by mhdzumair** [comment]
> 
> Some files were missing but dont worry I collected them. I want to know something every time I flash a custom kernel on this phone its either no volte or no usb otg/ usb storage even lsusb dosent show anything.
> 
> Should I flash magisk after kernel or before kernel and do i need dm-verity ?

volte bug not fix in custom rom. Only stock rom and miui custom rom only have volte. Join the telegram group to get the rom link. magisk is enough no need to dm-verity patch. No need to flash after every time you flash a new kernel. I'm using woods. I don't have a bug on USB otg. I'll check the USB issue. This is the telegram group link. https://t.me/Moto_E4_Plus_Custom_Roms
